#ifndef DECK_H_
#define DECK_H_

#include "card.h"
#define DECK_SIZE 40

static const Card CARD_SET[DECK_SIZE] = { {CARD_SUIT_HEARTS, CARD_RANK_ACE}, {CARD_SUIT_HEARTS, CARD_RANK_TWO}, {CARD_SUIT_HEARTS, CARD_RANK_THREE}, {CARD_SUIT_HEARTS, CARD_RANK_FOUR}, {CARD_SUIT_HEARTS, CARD_RANK_FIVE}, {CARD_SUIT_HEARTS, CARD_RANK_SIX}, {CARD_SUIT_HEARTS, CARD_RANK_SEVEN}, {CARD_SUIT_HEARTS, CARD_RANK_JACK}, {CARD_SUIT_HEARTS, CARD_RANK_QUEEN}, {CARD_SUIT_HEARTS, CARD_RANK_KING}, {CARD_SUIT_DIAMONDS, CARD_RANK_ACE}, {CARD_SUIT_DIAMONDS, CARD_RANK_TWO}, {CARD_SUIT_DIAMONDS, CARD_RANK_THREE}, {CARD_SUIT_DIAMONDS, CARD_RANK_FOUR}, {CARD_SUIT_DIAMONDS, CARD_RANK_FIVE}, {CARD_SUIT_DIAMONDS, CARD_RANK_SIX}, {CARD_SUIT_DIAMONDS, CARD_RANK_SEVEN}, {CARD_SUIT_DIAMONDS, CARD_RANK_JACK}, {CARD_SUIT_DIAMONDS, CARD_RANK_QUEEN}, {CARD_SUIT_DIAMONDS, CARD_RANK_KING}, {CARD_SUIT_CLUBS, CARD_RANK_ACE}, {CARD_SUIT_CLUBS, CARD_RANK_TWO}, {CARD_SUIT_CLUBS, CARD_RANK_THREE}, {CARD_SUIT_CLUBS, CARD_RANK_FOUR}, {CARD_SUIT_CLUBS, CARD_RANK_FIVE}, {CARD_SUIT_CLUBS, CARD_RANK_SIX}, {CARD_SUIT_CLUBS, CARD_RANK_SEVEN}, {CARD_SUIT_CLUBS, CARD_RANK_JACK}, {CARD_SUIT_CLUBS, CARD_RANK_QUEEN}, {CARD_SUIT_CLUBS, CARD_RANK_KING}, {CARD_SUIT_SPADES, CARD_RANK_ACE}, {CARD_SUIT_SPADES, CARD_RANK_TWO}, {CARD_SUIT_SPADES, CARD_RANK_THREE}, {CARD_SUIT_SPADES, CARD_RANK_FOUR}, {CARD_SUIT_SPADES, CARD_RANK_FIVE}, {CARD_SUIT_SPADES, CARD_RANK_SIX}, {CARD_SUIT_SPADES, CARD_RANK_SEVEN}, {CARD_SUIT_SPADES, CARD_RANK_JACK}, {CARD_SUIT_SPADES, CARD_RANK_QUEEN}, {CARD_SUIT_SPADES, CARD_RANK_KING} };

typedef struct _Deck {
    int cards[DECK_SIZE];
    int index;
} Deck;

void DECK_RNGInit(void);
Deck DECK_Create(void);
void DECK_Shuffle(Deck* d);
Card DECK_Pop(Deck* d);

#endif // DECK_H_