#include "deck.h"
#include "random.h"

static const Card CARD_SET[DECK_SIZE] = { {CARD_SUIT_HEARTS, CARD_RANK_ACE}, {CARD_SUIT_HEARTS, CARD_RANK_TWO}, {CARD_SUIT_HEARTS, CARD_RANK_THREE}, {CARD_SUIT_HEARTS, CARD_RANK_FOUR}, {CARD_SUIT_HEARTS, CARD_RANK_FIVE}, {CARD_SUIT_HEARTS, CARD_RANK_SIX}, {CARD_SUIT_HEARTS, CARD_RANK_SEVEN}, {CARD_SUIT_HEARTS, CARD_RANK_JACK}, {CARD_SUIT_HEARTS, CARD_RANK_QUEEN}, {CARD_SUIT_HEARTS, CARD_RANK_KING}, {CARD_SUIT_DIAMONDS, CARD_RANK_ACE}, {CARD_SUIT_DIAMONDS, CARD_RANK_TWO}, {CARD_SUIT_DIAMONDS, CARD_RANK_THREE}, {CARD_SUIT_DIAMONDS, CARD_RANK_FOUR}, {CARD_SUIT_DIAMONDS, CARD_RANK_FIVE}, {CARD_SUIT_DIAMONDS, CARD_RANK_SIX}, {CARD_SUIT_DIAMONDS, CARD_RANK_SEVEN}, {CARD_SUIT_DIAMONDS, CARD_RANK_JACK}, {CARD_SUIT_DIAMONDS, CARD_RANK_QUEEN}, {CARD_SUIT_DIAMONDS, CARD_RANK_KING}, {CARD_SUIT_CLUBS, CARD_RANK_ACE}, {CARD_SUIT_CLUBS, CARD_RANK_TWO}, {CARD_SUIT_CLUBS, CARD_RANK_THREE}, {CARD_SUIT_CLUBS, CARD_RANK_FOUR}, {CARD_SUIT_CLUBS, CARD_RANK_FIVE}, {CARD_SUIT_CLUBS, CARD_RANK_SIX}, {CARD_SUIT_CLUBS, CARD_RANK_SEVEN}, {CARD_SUIT_CLUBS, CARD_RANK_JACK}, {CARD_SUIT_CLUBS, CARD_RANK_QUEEN}, {CARD_SUIT_CLUBS, CARD_RANK_KING}, {CARD_SUIT_SPADES, CARD_RANK_ACE}, {CARD_SUIT_SPADES, CARD_RANK_TWO}, {CARD_SUIT_SPADES, CARD_RANK_THREE}, {CARD_SUIT_SPADES, CARD_RANK_FOUR}, {CARD_SUIT_SPADES, CARD_RANK_FIVE}, {CARD_SUIT_SPADES, CARD_RANK_SIX}, {CARD_SUIT_SPADES, CARD_RANK_SEVEN}, {CARD_SUIT_SPADES, CARD_RANK_JACK}, {CARD_SUIT_SPADES, CARD_RANK_QUEEN}, {CARD_SUIT_SPADES, CARD_RANK_KING} };

void DECK_Create(Deck* d) {
    for (int i = 0; i < DECK_SIZE; ++i)
        d->cards[i] = i;
    d->index = 0;
}

void DECK_Shuffle(Deck* d) {
    for (int i = 0; i < DECK_SIZE; ++i) {
        int j = RND_Get(0, DECK_SIZE - 1);
        int swap = d->cards[j];
        d->cards[j] = d->cards[i];
        d->cards[i] = swap;
    }
}

Card DECK_Pop(Deck* d) {
    if (d->index < DECK_SIZE)
        return CARD_SET[d->cards[d->index++]];
    else
        return NO_CARDS_LEFT;
}